version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: nest_test1_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  nest_test1:
    build:
      dockerfile: ./Dockerfile
    container_name: nest_test1
    volumes:
      - './:/app'
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - mysql

volumes:
  mysql-data:
